[package]
name = "streamthumb-cli"
description = "Command-line frontend for streamthumb"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "streamthumb"
path = "src/main.rs"

[dependencies]
streamthumb-core = { version = "0.2.0", path = "../streamthumb-core" }
streamthumb-png = { version = "0.2.0", path = "../streamthumb-png" }

[lints]
workspace = true
