[package]
name = "streamthumb-encode"
description = "Bounded streaming encoders for streamthumb"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
jpeg-encoder = { version = "=0.6.1", default-features = false, features = ["std"] }
streamthumb-core = { version = "0.1.0", path = "../streamthumb-core" }

[dev-dependencies]
jpeg-decoder = "0.3.2"

[lints]
workspace = true
